minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@es-joy/jsdoccomment'
  - '@kazupon/jts-utils'
  - '@kazupon/eslint-plugin'
  - eslint
  - svelte
  - tsdown
  - knip
  - prettier
  - typescript
  - typescript-eslint
  - vitest
